export default async () => {
  //console.log("passe no list frases!!!")
  const phrases = [
"Hello! - Olá!",
"How are you? - Como você está?",
"Good morning! - Bom dia!",
"Good night! - Boa noite!",
"Thank you! - Obrigado(a)!",
"Please. - Por favor.",
"Excuse me. - Com licença.",
"I'm sorry. - Desculpe-me.",
"What's your name? - Qual é o seu nome?",
"Nice to meet you! - Prazer em conhecê-lo(a)!",
"How much is this? - Quanto custa isso?",
"Where is the bathroom? - Onde fica o banheiro?",
"I don't understand. - Eu não entendo.",
"Could you repeat that, please? - Você poderia repetir, por favor?",
"Can you help me? - Você pode me ajudar?",
"I'm looking for... - Estou procurando por...",
"What time is it? - Que horas são?",
"See you later! - Até mais!",
"Have a nice day! - Tenha um bom dia!",
"I would like... - Eu gostaria de...",
"Where are you from? - De onde você é?",
"Can I have the bill, please? - Posso ter a conta, por favor?",
"I'm lost. - Estou perdido(a).",
"I'm hungry. - Estou com fome.",
"I'm thirsty. - Estou com sede.",
"Can I try this on? - Posso experimentar isso?",
"I don't know. - Eu não sei.",
"It's okay. - Está tudo bem.",
"What do you do for a living? - O que você faz para viver?",
"I love you. - Eu te amo.",
"Where do you live? - Onde você mora?",
"How old are you? - Quantos anos você tem?",
"I'm tired. - Estou cansado(a).",
"I'm happy. - Estou feliz.",
"I'm sad. - Estou triste.",
"What is your phone number? - Qual é o seu número de telefone?",
"Can you speak English? - Você fala inglês?",
"I don't speak much English. - Eu não falo muito inglês.",
"I need help. - Eu preciso de ajuda.",
"Where can I find...? - Onde eu posso encontrar...?",
"Can I have some water? - Posso ter um pouco de água?",
"What is your favorite color? - Qual é a sua cor favorita?",
"Do you like it? - Você gosta disso?",
"What do you think? - O que você acha?",
"I don't care. - Eu não me importo.",
"I'm fine, thank you. - Estou bem, obrigado(a).",
"Let's go! - Vamos!",
"What are you doing? - O que você está fazendo?",
"How do you say... in English? - Como se diz... em inglês?",
"I need to go now. - Eu preciso ir agora.",
"What do you mean? - O que você quer dizer?",
"I'm late. - Estou atrasado(a).",
"Don't worry. - Não se preocupe.",
"Everything will be okay. - Tudo vai ficar bem.",
"Can I ask you a question? - Posso te fazer uma pergunta?",
"Can I sit here? - Posso sentar aqui?",
"What's wrong? - O que há de errado?",
"Do you need anything? - Você precisa de alguma coisa?",
"How do you spell that? - Como se soletra isso?",
"I don't believe it! - Eu não acredito!",
"Can you show me? - Você pode me mostrar?",
"That's interesting. - Isso é interessante.",
"I'm bored. - Estou entediado(a).",
"I'm busy. - Estou ocupado(a).",
"Can you drive? - Você pode dirigir?",
"Be careful! - Tenha cuidado!",
"That's enough. - Isso é o suficiente.",
"It's not fair. - Isso não é justo.",
"I agree. - Eu concordo.",
"I disagree. - Eu discordo.",
"It's too expensive. - É muito caro.",
"I'm not sure. - Eu não tenho certeza.",
"It's my turn. - É a minha vez.",
"It's your turn. - É a sua vez.",
"I'm coming. - Estou indo.",
"Do you understand? - Você entende?",
"Can you wait a moment? - Você pode esperar um momento?",
"What's the problem? - Qual é o problema?",
"Let's start. - Vamos começar.",
"It's time to go. - É hora de ir.",

    ]
  return phrases[Math.floor(Math.random() * phrases.length)]

}
