name: Build and deploy api

on:
  push:
    branches:
      - main-ai-cob

jobs:
  build:
    name: Build api typescript project and deploy it to server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Git user
        run: |
          git config --global user.email "brunofa23@gmail.com"
          git config --global user.name "Bruno Favato"

      # Checkout branch de produção
      - name: Checkout production-ai-cob
        run: git checkout production-ai-cob

      # Puxa mudanças mais recentes
      - name: Pull latest changes from production-ai-cob
        run: git pull

      # Faz merge com a branch de origem
      - name: Merge changes from main-ai-cob
        run: git merge main-ai-cob

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Build (aqui dispara o postbuild automaticamente)
      - name: Build project
        run: npm run build

      # Instala dependências de produção na build
      - name: Install production dependencies
        run: npm ci --production --prefix ./build

      # Commita resultado gerado
      - name: Git add build output
        run: git add -A

      - name: Git commit
        run: |
          git commit -m 'nova versão' || echo "Nada para commitar"

      - name: Push to production-ai-cob
        run: git push origin production-ai-cob
