name: Delete and Merge

on:
  push:
    branches:
      - development

jobs:
  delete_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Configure git user credentials
        run: |
          git config --global user.email "brunofa23@gmail.com"
          git config --global user.name "Bruno Favato"

      - name: Checkout main-production branch
        uses: actions/checkout@v2
        with:
          ref: development

        run: git status
      - name: Checkout main
        run: git checkout main

      - name: Git Pull
        run: git pull

      - name: Merge main into main-production
        run: git merge development

      - name: Push changes to main-production branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main-production
